### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by shelcia** [shelcia/noobcodes-docs#51]
https://docusaurus.io/docs/search

**Comment by shivamgupta2020** [comment]
I had gone through the above documentation and found a local search plugin.
[https://github.com/praveenn77/docusaurus-lunr-search](url)
But the problem is it doesn't work on development. It works nicely in build.
Algolia search is an option but it might take some time as we need to apply for search plugin.
Other options are not suitable for this project.
What to do now?

**Comment by shivamgupta2020** [comment]
can't we use build here?

**Comment by shivamgupta2020** [comment]
if we use `npm build`  and then `npx http-server ./build` it will work

**Comment by shivamgupta2020** [comment]
> Owner

ok then I will work on another issue.
Tag me when u apply for algolia docsearch.

**Comment by shelcia** [comment]
Sure

**Comment by ankushj0801** [comment]
can I work on this if it is open? @shelcia

**Comment by shelcia** [comment]
Algolia is implemented !
